name: buildx my image

on:
  push:
    branches: main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: install buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          version: latest
      - name: build the image hello_world
      run: |
        docker buildx build --push \
          --tag antonyxu/hello_world:latest \
          --platform linux/amd64,linux/arm/v7,linux/arm64 ./hello_world
